export enum GAME_EVENT {
  CELL_REVEALED = 'CELL_REVEALED',
  BET_PLACED = 'BET_PLACED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_OVER = 'GAME_OVER',
  CASHED_OUT = 'CASHED_OUT',
  POTENTIAL_WIN_UPDATED = 'POTENTIAL_WIN_UPDATED',
  BALANCE_UPDATED = 'BALANCE_UPDATED',
}
